language: swift
osx_image: xcode10.1
script:
    - carthage update --platform macOS
    - xcodebuild test -project Thesi.xcodeproj -scheme Thesi -destination 'platform=macOS' -configuration Travis | xcpretty