language: swift
osx_image: xcode10.1

addons:
  sonarcloud:
    organization: "chriszielinski-github"

script:
    - make carthage
    - make test
    - swiftlint
    - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)